/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:56 2019. */

#ifndef PB_PROTO_ASEFEP_ASE_FEP_REQRESP_PB_H_INCLUDED
#define PB_PROTO_ASEFEP_ASE_FEP_REQRESP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Proto_AseFep_ReqResp {
    Proto_AseFep_ReqResp_POWER_REQUEST = 7,
    Proto_AseFep_ReqResp_AUDIO_MODE = 8,
    Proto_AseFep_ReqResp_AUDIO_INPUT = 9,
    Proto_AseFep_ReqResp_POSITION_SOUND_MODE = 10,
    Proto_AseFep_ReqResp_INTERNAL_SPEAKER_COMPENSATION = 11,
    Proto_AseFep_ReqResp_DSP_PARAMETER = 45,
    Proto_AseFep_ReqResp_DSP_VOLUME_FADE = 56,
    Proto_AseFep_ReqResp_DSP_GET_INTERNAL_SPEAKER_COMPENSATION = 86,
    Proto_AseFep_ReqResp_DSP_GET_SPEAKER_POSITION = 88
} Proto_AseFep_ReqResp;
#define _Proto_AseFep_ReqResp_MIN Proto_AseFep_ReqResp_POWER_REQUEST
#define _Proto_AseFep_ReqResp_MAX Proto_AseFep_ReqResp_DSP_GET_SPEAKER_POSITION
#define _Proto_AseFep_ReqResp_ARRAYSIZE ((Proto_AseFep_ReqResp)(Proto_AseFep_ReqResp_DSP_GET_SPEAKER_POSITION+1))

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
