/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:56 2019. */

#ifndef PB_PROTO_CORE_COMMON_PB_H_INCLUDED
#define PB_PROTO_CORE_COMMON_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Proto_Core_GenericResponse_Status {
    Proto_Core_GenericResponse_Status_DONE = 0,
    Proto_Core_GenericResponse_Status_ERROR = 1,
    Proto_Core_GenericResponse_Status_NOT_SUPPORTED = 2,
    Proto_Core_GenericResponse_Status_UNKNOWN_REQUEST = 3
} Proto_Core_GenericResponse_Status;
#define _Proto_Core_GenericResponse_Status_MIN Proto_Core_GenericResponse_Status_DONE
#define _Proto_Core_GenericResponse_Status_MAX Proto_Core_GenericResponse_Status_UNKNOWN_REQUEST
#define _Proto_Core_GenericResponse_Status_ARRAYSIZE ((Proto_Core_GenericResponse_Status)(Proto_Core_GenericResponse_Status_UNKNOWN_REQUEST+1))

/* Struct definitions */
typedef struct _Proto_Core_GenericResponse {
    bool has_status;
    Proto_Core_GenericResponse_Status status;
/* @@protoc_insertion_point(struct:Proto_Core_GenericResponse) */
} Proto_Core_GenericResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Proto_Core_GenericResponse_init_default  {false, (Proto_Core_GenericResponse_Status)0}
#define Proto_Core_GenericResponse_init_zero     {false, (Proto_Core_GenericResponse_Status)0}

/* Field tags (for use in manual encoding/decoding) */
#define Proto_Core_GenericResponse_status_tag    1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Proto_Core_GenericResponse_fields[2];

/* Maximum encoded size of messages (where known) */
#define Proto_Core_GenericResponse_size          2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COMMON_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
