/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:58 2019. */

#ifndef PB_PROTO_DSP_DSP_PB_H_INCLUDED
#define PB_PROTO_DSP_DSP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Proto_Dsp_AudioMode_AudioMode {
    Proto_Dsp_AudioMode_AudioMode_ENTERTAINMENT = 0,
    Proto_Dsp_AudioMode_AudioMode_MASSAGE = 1
} Proto_Dsp_AudioMode_AudioMode;
#define _Proto_Dsp_AudioMode_AudioMode_MIN Proto_Dsp_AudioMode_AudioMode_ENTERTAINMENT
#define _Proto_Dsp_AudioMode_AudioMode_MAX Proto_Dsp_AudioMode_AudioMode_MASSAGE
#define _Proto_Dsp_AudioMode_AudioMode_ARRAYSIZE ((Proto_Dsp_AudioMode_AudioMode)(Proto_Dsp_AudioMode_AudioMode_MASSAGE+1))

typedef enum _Proto_Dsp_RequestAudioInput_AudioInput {
    Proto_Dsp_RequestAudioInput_AudioInput_WIFIBT = 0,
    Proto_Dsp_RequestAudioInput_AudioInput_SDCARD = 1,
    Proto_Dsp_RequestAudioInput_AudioInput_LINE = 2
} Proto_Dsp_RequestAudioInput_AudioInput;
#define _Proto_Dsp_RequestAudioInput_AudioInput_MIN Proto_Dsp_RequestAudioInput_AudioInput_WIFIBT
#define _Proto_Dsp_RequestAudioInput_AudioInput_MAX Proto_Dsp_RequestAudioInput_AudioInput_LINE
#define _Proto_Dsp_RequestAudioInput_AudioInput_ARRAYSIZE ((Proto_Dsp_RequestAudioInput_AudioInput)(Proto_Dsp_RequestAudioInput_AudioInput_LINE+1))

typedef enum _Proto_Dsp_PositionSoundMode_Position {
    Proto_Dsp_PositionSoundMode_Position_UNDEFINED = 0,
    Proto_Dsp_PositionSoundMode_Position_FREE = 1,
    Proto_Dsp_PositionSoundMode_Position_WALL = 2,
    Proto_Dsp_PositionSoundMode_Position_CORNER = 3,
    Proto_Dsp_PositionSoundMode_Position_TABLE = 4
} Proto_Dsp_PositionSoundMode_Position;
#define _Proto_Dsp_PositionSoundMode_Position_MIN Proto_Dsp_PositionSoundMode_Position_UNDEFINED
#define _Proto_Dsp_PositionSoundMode_Position_MAX Proto_Dsp_PositionSoundMode_Position_TABLE
#define _Proto_Dsp_PositionSoundMode_Position_ARRAYSIZE ((Proto_Dsp_PositionSoundMode_Position)(Proto_Dsp_PositionSoundMode_Position_TABLE+1))

typedef enum _Proto_Dsp_PositionSoundMode_Orientation {
    Proto_Dsp_PositionSoundMode_Orientation_NONE = 0,
    Proto_Dsp_PositionSoundMode_Orientation_HORIZONTAL = 1,
    Proto_Dsp_PositionSoundMode_Orientation_VERTICAL = 2
} Proto_Dsp_PositionSoundMode_Orientation;
#define _Proto_Dsp_PositionSoundMode_Orientation_MIN Proto_Dsp_PositionSoundMode_Orientation_NONE
#define _Proto_Dsp_PositionSoundMode_Orientation_MAX Proto_Dsp_PositionSoundMode_Orientation_VERTICAL
#define _Proto_Dsp_PositionSoundMode_Orientation_ARRAYSIZE ((Proto_Dsp_PositionSoundMode_Orientation)(Proto_Dsp_PositionSoundMode_Orientation_VERTICAL+1))

typedef enum _Proto_Dsp_ResponsePositionSoundMode_Error {
    Proto_Dsp_ResponsePositionSoundMode_Error_NO_ERROR = 1,
    Proto_Dsp_ResponsePositionSoundMode_Error_POSITION_ERROR = 2,
    Proto_Dsp_ResponsePositionSoundMode_Error_ORIENTATION_ERROR = 3,
    Proto_Dsp_ResponsePositionSoundMode_Error_COMBINATION_ERROR = 4
} Proto_Dsp_ResponsePositionSoundMode_Error;
#define _Proto_Dsp_ResponsePositionSoundMode_Error_MIN Proto_Dsp_ResponsePositionSoundMode_Error_NO_ERROR
#define _Proto_Dsp_ResponsePositionSoundMode_Error_MAX Proto_Dsp_ResponsePositionSoundMode_Error_COMBINATION_ERROR
#define _Proto_Dsp_ResponsePositionSoundMode_Error_ARRAYSIZE ((Proto_Dsp_ResponsePositionSoundMode_Error)(Proto_Dsp_ResponsePositionSoundMode_Error_COMBINATION_ERROR+1))

typedef enum _Proto_Dsp_InternalSpeaker_Position {
    Proto_Dsp_InternalSpeaker_Position_LEFT = 0,
    Proto_Dsp_InternalSpeaker_Position_RIGHT = 1,
    Proto_Dsp_InternalSpeaker_Position_CENTRE = 2
} Proto_Dsp_InternalSpeaker_Position;
#define _Proto_Dsp_InternalSpeaker_Position_MIN Proto_Dsp_InternalSpeaker_Position_LEFT
#define _Proto_Dsp_InternalSpeaker_Position_MAX Proto_Dsp_InternalSpeaker_Position_CENTRE
#define _Proto_Dsp_InternalSpeaker_Position_ARRAYSIZE ((Proto_Dsp_InternalSpeaker_Position)(Proto_Dsp_InternalSpeaker_Position_CENTRE+1))

typedef enum _Proto_Dsp_InternalSpeaker_Type {
    Proto_Dsp_InternalSpeaker_Type_TWEETER = 0,
    Proto_Dsp_InternalSpeaker_Type_MIDRANGE = 1,
    Proto_Dsp_InternalSpeaker_Type_WOOFER = 2,
    Proto_Dsp_InternalSpeaker_Type_FULLRANGE = 3
} Proto_Dsp_InternalSpeaker_Type;
#define _Proto_Dsp_InternalSpeaker_Type_MIN Proto_Dsp_InternalSpeaker_Type_TWEETER
#define _Proto_Dsp_InternalSpeaker_Type_MAX Proto_Dsp_InternalSpeaker_Type_FULLRANGE
#define _Proto_Dsp_InternalSpeaker_Type_ARRAYSIZE ((Proto_Dsp_InternalSpeaker_Type)(Proto_Dsp_InternalSpeaker_Type_FULLRANGE+1))

typedef enum _Proto_Dsp_ResponseInternalSpeakerCompensation_Error {
    Proto_Dsp_ResponseInternalSpeakerCompensation_Error_NO_ERROR = 1,
    Proto_Dsp_ResponseInternalSpeakerCompensation_Error_POSITION_ERROR = 2,
    Proto_Dsp_ResponseInternalSpeakerCompensation_Error_TYPE_ERROR = 3,
    Proto_Dsp_ResponseInternalSpeakerCompensation_Error_POSITION_TYPE_COMBINATION_ERROR = 4,
    Proto_Dsp_ResponseInternalSpeakerCompensation_Error_GAIN_ERROR = 5
} Proto_Dsp_ResponseInternalSpeakerCompensation_Error;
#define _Proto_Dsp_ResponseInternalSpeakerCompensation_Error_MIN Proto_Dsp_ResponseInternalSpeakerCompensation_Error_NO_ERROR
#define _Proto_Dsp_ResponseInternalSpeakerCompensation_Error_MAX Proto_Dsp_ResponseInternalSpeakerCompensation_Error_GAIN_ERROR
#define _Proto_Dsp_ResponseInternalSpeakerCompensation_Error_ARRAYSIZE ((Proto_Dsp_ResponseInternalSpeakerCompensation_Error)(Proto_Dsp_ResponseInternalSpeakerCompensation_Error_GAIN_ERROR+1))

typedef enum _Proto_Dsp_Parameter_Type {
    Proto_Dsp_Parameter_Type_LOUDNESS = 0,
    Proto_Dsp_Parameter_Type_BASS = 1,
    Proto_Dsp_Parameter_Type_TREBLE = 2
} Proto_Dsp_Parameter_Type;
#define _Proto_Dsp_Parameter_Type_MIN Proto_Dsp_Parameter_Type_LOUDNESS
#define _Proto_Dsp_Parameter_Type_MAX Proto_Dsp_Parameter_Type_TREBLE
#define _Proto_Dsp_Parameter_Type_ARRAYSIZE ((Proto_Dsp_Parameter_Type)(Proto_Dsp_Parameter_Type_TREBLE+1))

/* Struct definitions */
typedef struct _Proto_Dsp_AbsoluteVolume {
    bool has_volume;
    uint32_t volume;
    bool has_fade_duration;
    uint32_t fade_duration;
/* @@protoc_insertion_point(struct:Proto_Dsp_AbsoluteVolume) */
} Proto_Dsp_AbsoluteVolume;

typedef struct _Proto_Dsp_AudioMode {
    bool has_mode;
    Proto_Dsp_AudioMode_AudioMode mode;
/* @@protoc_insertion_point(struct:Proto_Dsp_AudioMode) */
} Proto_Dsp_AudioMode;

typedef struct _Proto_Dsp_InternalSpeaker {
    bool has_position;
    Proto_Dsp_InternalSpeaker_Position position;
    bool has_type;
    Proto_Dsp_InternalSpeaker_Type type;
    bool has_compensation;
    double compensation;
/* @@protoc_insertion_point(struct:Proto_Dsp_InternalSpeaker) */
} Proto_Dsp_InternalSpeaker;

typedef struct _Proto_Dsp_Mute {
    bool has_mute;
    bool mute;
/* @@protoc_insertion_point(struct:Proto_Dsp_Mute) */
} Proto_Dsp_Mute;

typedef struct _Proto_Dsp_Parameter {
    bool has_type;
    Proto_Dsp_Parameter_Type type;
    bool has_value;
    int32_t value;
/* @@protoc_insertion_point(struct:Proto_Dsp_Parameter) */
} Proto_Dsp_Parameter;

typedef struct _Proto_Dsp_PositionSoundMode {
    bool has_position;
    Proto_Dsp_PositionSoundMode_Position position;
    bool has_orientation;
    Proto_Dsp_PositionSoundMode_Orientation orientation;
/* @@protoc_insertion_point(struct:Proto_Dsp_PositionSoundMode) */
} Proto_Dsp_PositionSoundMode;

typedef struct _Proto_Dsp_RelativeVolumeChange {
    bool has_volumeChange;
    int32_t volumeChange;
/* @@protoc_insertion_point(struct:Proto_Dsp_RelativeVolumeChange) */
} Proto_Dsp_RelativeVolumeChange;

typedef struct _Proto_Dsp_RequestAudioInput {
    bool has_input;
    Proto_Dsp_RequestAudioInput_AudioInput input;
/* @@protoc_insertion_point(struct:Proto_Dsp_RequestAudioInput) */
} Proto_Dsp_RequestAudioInput;

typedef struct _Proto_Dsp_ToneTouch {
    bool has_Gx1;
    double Gx1;
    bool has_Gy1;
    double Gy1;
    bool has_Gx2;
    double Gx2;
    bool has_Gy2;
    double Gy2;
    bool has_Gz;
    double Gz;
    bool has_k5;
    double k5;
    bool has_k6;
    double k6;
    bool has_enabled;
    bool enabled;
/* @@protoc_insertion_point(struct:Proto_Dsp_ToneTouch) */
} Proto_Dsp_ToneTouch;

typedef struct _Proto_Dsp_RequestInternalSpeakerCompensation {
    Proto_Dsp_InternalSpeaker internalSpeaker;
/* @@protoc_insertion_point(struct:Proto_Dsp_RequestInternalSpeakerCompensation) */
} Proto_Dsp_RequestInternalSpeakerCompensation;

typedef struct _Proto_Dsp_RequestPositionSoundMode {
    bool has_positionSoundMode;
    Proto_Dsp_PositionSoundMode positionSoundMode;
/* @@protoc_insertion_point(struct:Proto_Dsp_RequestPositionSoundMode) */
} Proto_Dsp_RequestPositionSoundMode;

typedef struct _Proto_Dsp_ResponseInternalSpeakerCompensation {
    bool has_error;
    Proto_Dsp_ResponseInternalSpeakerCompensation_Error error;
    Proto_Dsp_InternalSpeaker internalSpeaker;
/* @@protoc_insertion_point(struct:Proto_Dsp_ResponseInternalSpeakerCompensation) */
} Proto_Dsp_ResponseInternalSpeakerCompensation;

typedef struct _Proto_Dsp_ResponsePositionSoundMode {
    bool has_error;
    Proto_Dsp_ResponsePositionSoundMode_Error error;
    bool has_mode;
    Proto_Dsp_PositionSoundMode mode;
/* @@protoc_insertion_point(struct:Proto_Dsp_ResponsePositionSoundMode) */
} Proto_Dsp_ResponsePositionSoundMode;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Proto_Dsp_AudioMode_init_default         {false, (Proto_Dsp_AudioMode_AudioMode)0}
#define Proto_Dsp_AbsoluteVolume_init_default    {false, 0, false, 0}
#define Proto_Dsp_RelativeVolumeChange_init_default {false, 0}
#define Proto_Dsp_Mute_init_default              {false, 0}
#define Proto_Dsp_RequestAudioInput_init_default {false, (Proto_Dsp_RequestAudioInput_AudioInput)0}
#define Proto_Dsp_PositionSoundMode_init_default {false, (Proto_Dsp_PositionSoundMode_Position)0, false, (Proto_Dsp_PositionSoundMode_Orientation)0}
#define Proto_Dsp_RequestPositionSoundMode_init_default {false, Proto_Dsp_PositionSoundMode_init_default}
#define Proto_Dsp_ResponsePositionSoundMode_init_default {false, (Proto_Dsp_ResponsePositionSoundMode_Error)0, false, Proto_Dsp_PositionSoundMode_init_default}
#define Proto_Dsp_InternalSpeaker_init_default   {false, (Proto_Dsp_InternalSpeaker_Position)0, false, (Proto_Dsp_InternalSpeaker_Type)0, false, 0}
#define Proto_Dsp_RequestInternalSpeakerCompensation_init_default {Proto_Dsp_InternalSpeaker_init_default}
#define Proto_Dsp_ResponseInternalSpeakerCompensation_init_default {false, (Proto_Dsp_ResponseInternalSpeakerCompensation_Error)0, Proto_Dsp_InternalSpeaker_init_default}
#define Proto_Dsp_Parameter_init_default         {false, (Proto_Dsp_Parameter_Type)0, false, 0}
#define Proto_Dsp_ToneTouch_init_default         {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Proto_Dsp_AudioMode_init_zero            {false, (Proto_Dsp_AudioMode_AudioMode)0}
#define Proto_Dsp_AbsoluteVolume_init_zero       {false, 0, false, 0}
#define Proto_Dsp_RelativeVolumeChange_init_zero {false, 0}
#define Proto_Dsp_Mute_init_zero                 {false, 0}
#define Proto_Dsp_RequestAudioInput_init_zero    {false, (Proto_Dsp_RequestAudioInput_AudioInput)0}
#define Proto_Dsp_PositionSoundMode_init_zero    {false, (Proto_Dsp_PositionSoundMode_Position)0, false, (Proto_Dsp_PositionSoundMode_Orientation)0}
#define Proto_Dsp_RequestPositionSoundMode_init_zero {false, Proto_Dsp_PositionSoundMode_init_zero}
#define Proto_Dsp_ResponsePositionSoundMode_init_zero {false, (Proto_Dsp_ResponsePositionSoundMode_Error)0, false, Proto_Dsp_PositionSoundMode_init_zero}
#define Proto_Dsp_InternalSpeaker_init_zero      {false, (Proto_Dsp_InternalSpeaker_Position)0, false, (Proto_Dsp_InternalSpeaker_Type)0, false, 0}
#define Proto_Dsp_RequestInternalSpeakerCompensation_init_zero {Proto_Dsp_InternalSpeaker_init_zero}
#define Proto_Dsp_ResponseInternalSpeakerCompensation_init_zero {false, (Proto_Dsp_ResponseInternalSpeakerCompensation_Error)0, Proto_Dsp_InternalSpeaker_init_zero}
#define Proto_Dsp_Parameter_init_zero            {false, (Proto_Dsp_Parameter_Type)0, false, 0}
#define Proto_Dsp_ToneTouch_init_zero            {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Proto_Dsp_AbsoluteVolume_volume_tag      1
#define Proto_Dsp_AbsoluteVolume_fade_duration_tag 2
#define Proto_Dsp_AudioMode_mode_tag             1
#define Proto_Dsp_InternalSpeaker_position_tag   1
#define Proto_Dsp_InternalSpeaker_type_tag       2
#define Proto_Dsp_InternalSpeaker_compensation_tag 3
#define Proto_Dsp_Mute_mute_tag                  1
#define Proto_Dsp_Parameter_type_tag             1
#define Proto_Dsp_Parameter_value_tag            2
#define Proto_Dsp_PositionSoundMode_position_tag 1
#define Proto_Dsp_PositionSoundMode_orientation_tag 2
#define Proto_Dsp_RelativeVolumeChange_volumeChange_tag 1
#define Proto_Dsp_RequestAudioInput_input_tag    1
#define Proto_Dsp_ToneTouch_Gx1_tag              1
#define Proto_Dsp_ToneTouch_Gy1_tag              2
#define Proto_Dsp_ToneTouch_Gx2_tag              3
#define Proto_Dsp_ToneTouch_Gy2_tag              4
#define Proto_Dsp_ToneTouch_Gz_tag               5
#define Proto_Dsp_ToneTouch_k5_tag               6
#define Proto_Dsp_ToneTouch_k6_tag               7
#define Proto_Dsp_ToneTouch_enabled_tag          8
#define Proto_Dsp_RequestInternalSpeakerCompensation_internalSpeaker_tag 1
#define Proto_Dsp_RequestPositionSoundMode_positionSoundMode_tag 1
#define Proto_Dsp_ResponseInternalSpeakerCompensation_error_tag 1
#define Proto_Dsp_ResponseInternalSpeakerCompensation_internalSpeaker_tag 2
#define Proto_Dsp_ResponsePositionSoundMode_error_tag 1
#define Proto_Dsp_ResponsePositionSoundMode_mode_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Proto_Dsp_AudioMode_fields[2];
extern const pb_field_t Proto_Dsp_AbsoluteVolume_fields[3];
extern const pb_field_t Proto_Dsp_RelativeVolumeChange_fields[2];
extern const pb_field_t Proto_Dsp_Mute_fields[2];
extern const pb_field_t Proto_Dsp_RequestAudioInput_fields[2];
extern const pb_field_t Proto_Dsp_PositionSoundMode_fields[3];
extern const pb_field_t Proto_Dsp_RequestPositionSoundMode_fields[2];
extern const pb_field_t Proto_Dsp_ResponsePositionSoundMode_fields[3];
extern const pb_field_t Proto_Dsp_InternalSpeaker_fields[4];
extern const pb_field_t Proto_Dsp_RequestInternalSpeakerCompensation_fields[2];
extern const pb_field_t Proto_Dsp_ResponseInternalSpeakerCompensation_fields[3];
extern const pb_field_t Proto_Dsp_Parameter_fields[3];
extern const pb_field_t Proto_Dsp_ToneTouch_fields[9];

/* Maximum encoded size of messages (where known) */
#define Proto_Dsp_AudioMode_size                 2
#define Proto_Dsp_AbsoluteVolume_size            12
#define Proto_Dsp_RelativeVolumeChange_size      11
#define Proto_Dsp_Mute_size                      2
#define Proto_Dsp_RequestAudioInput_size         2
#define Proto_Dsp_PositionSoundMode_size         4
#define Proto_Dsp_RequestPositionSoundMode_size  6
#define Proto_Dsp_ResponsePositionSoundMode_size 8
#define Proto_Dsp_InternalSpeaker_size           13
#define Proto_Dsp_RequestInternalSpeakerCompensation_size 15
#define Proto_Dsp_ResponseInternalSpeakerCompensation_size 17
#define Proto_Dsp_Parameter_size                 13
#define Proto_Dsp_ToneTouch_size                 65

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DSP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
