/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:59 2019. */

#ifndef PB_PROTO_FEPASE_FEP_ASE_REQRESP_PB_H_INCLUDED
#define PB_PROTO_FEPASE_FEP_ASE_REQRESP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Proto_FepAse_ReqResp {
    Proto_FepAse_ReqResp_PING = 0
} Proto_FepAse_ReqResp;
#define _Proto_FepAse_ReqResp_MIN Proto_FepAse_ReqResp_PING
#define _Proto_FepAse_ReqResp_MAX Proto_FepAse_ReqResp_PING
#define _Proto_FepAse_ReqResp_ARRAYSIZE ((Proto_FepAse_ReqResp)(Proto_FepAse_ReqResp_PING+1))

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
