/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:52:00 2019. */

#ifndef PB_PROTO_PLAYER_PLAYER_PB_H_INCLUDED
#define PB_PROTO_PLAYER_PLAYER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Proto_Player_Data_State {
    Proto_Player_Data_State_PLAYING = 0,
    Proto_Player_Data_State_PAUSED = 1,
    Proto_Player_Data_State_STOPPED = 2
} Proto_Player_Data_State;
#define _Proto_Player_Data_State_MIN Proto_Player_Data_State_PLAYING
#define _Proto_Player_Data_State_MAX Proto_Player_Data_State_STOPPED
#define _Proto_Player_Data_State_ARRAYSIZE ((Proto_Player_Data_State)(Proto_Player_Data_State_STOPPED+1))

typedef enum _Proto_Player_Data_Source {
    Proto_Player_Data_Source_UNKNOWN = 0,
    Proto_Player_Data_Source_BLUETOOTH = 1
} Proto_Player_Data_Source;
#define _Proto_Player_Data_Source_MIN Proto_Player_Data_Source_UNKNOWN
#define _Proto_Player_Data_Source_MAX Proto_Player_Data_Source_BLUETOOTH
#define _Proto_Player_Data_Source_ARRAYSIZE ((Proto_Player_Data_Source)(Proto_Player_Data_Source_BLUETOOTH+1))

/* Struct definitions */
typedef struct _Proto_Player_Data {
    bool has_state;
    Proto_Player_Data_State state;
    bool has_source;
    Proto_Player_Data_Source source;
/* @@protoc_insertion_point(struct:Proto_Player_Data) */
} Proto_Player_Data;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Proto_Player_Data_init_default           {false, (Proto_Player_Data_State)0, false, (Proto_Player_Data_Source)0}
#define Proto_Player_Data_init_zero              {false, (Proto_Player_Data_State)0, false, (Proto_Player_Data_Source)0}

/* Field tags (for use in manual encoding/decoding) */
#define Proto_Player_Data_state_tag              1
#define Proto_Player_Data_source_tag             2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Proto_Player_Data_fields[3];

/* Maximum encoded size of messages (where known) */
#define Proto_Player_Data_size                   4

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PLAYER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
