/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:52:01 2019. */

#ifndef PB_PROTO_SYSTEM_SYSTEM_PB_H_INCLUDED
#define PB_PROTO_SYSTEM_SYSTEM_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Proto_System_Overheat {
    int32_t amp1;
    int32_t amp2;
    int32_t wfl;
    int32_t wfr;
/* @@protoc_insertion_point(struct:Proto_System_Overheat) */
} Proto_System_Overheat;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Proto_System_Overheat_init_default       {0, 0, 0, 0}
#define Proto_System_Overheat_init_zero          {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Proto_System_Overheat_amp1_tag           1
#define Proto_System_Overheat_amp2_tag           2
#define Proto_System_Overheat_wfl_tag            3
#define Proto_System_Overheat_wfr_tag            4

/* Struct field encoding specification for nanopb */
extern const pb_field_t Proto_System_Overheat_fields[5];

/* Maximum encoded size of messages (where known) */
#define Proto_System_Overheat_size               44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SYSTEM_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
