/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:55 2019. */

#include "ase-fep.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_AseFep_Req_fields[9] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_AseFep_Req, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_AseFep_Req, id, type, 0),
    PB_ONEOF_FIELD(data,  12, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Req, audioMode, id, &Proto_Dsp_AudioMode_fields),
    PB_ONEOF_FIELD(data,  13, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Req, audioInput, id, &Proto_Dsp_RequestAudioInput_fields),
    PB_ONEOF_FIELD(data,  14, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Req, positionSoundMode, id, &Proto_Dsp_RequestPositionSoundMode_fields),
    PB_ONEOF_FIELD(data,  15, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Req, internalSpeakerCompensation, id, &Proto_Dsp_RequestInternalSpeakerCompensation_fields),
    PB_ONEOF_FIELD(data,  35, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Req, dspParameter, id, &Proto_Dsp_Parameter_fields),
    PB_ONEOF_FIELD(data,  40, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Req, dspAbsoluteVolume, id, &Proto_Dsp_AbsoluteVolume_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_AseFep_Resp_fields[5] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_AseFep_Resp, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_AseFep_Resp, id, type, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Proto_AseFep_Resp, genericResponse, id, &Proto_Core_GenericResponse_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Resp, volume, genericResponse, &Proto_Dsp_AbsoluteVolume_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_AseFep_Event_fields[7] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_AseFep_Event, type, type, 0),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Event, productionTunnel, type, &Proto_Production_Tunnel_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Event, volume, type, &Proto_Dsp_AbsoluteVolume_fields),
    PB_ONEOF_FIELD(data,  12, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Event, mute, type, &Proto_Dsp_Mute_fields),
    PB_ONEOF_FIELD(data,  14, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Event, playerData, type, &Proto_Player_Data_fields),
    PB_ONEOF_FIELD(data,  15, MESSAGE , ONEOF, STATIC  , OTHER, Proto_AseFep_Event, dspToneTouch, type, &Proto_Dsp_ToneTouch_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_AseFep_Req, data.audioMode) < 65536 && pb_membersize(Proto_AseFep_Req, data.audioInput) < 65536 && pb_membersize(Proto_AseFep_Req, data.positionSoundMode) < 65536 && pb_membersize(Proto_AseFep_Req, data.internalSpeakerCompensation) < 65536 && pb_membersize(Proto_AseFep_Req, data.dspParameter) < 65536 && pb_membersize(Proto_AseFep_Req, data.dspAbsoluteVolume) < 65536 && pb_membersize(Proto_AseFep_Resp, data.volume) < 65536 && pb_membersize(Proto_AseFep_Resp, genericResponse) < 65536 && pb_membersize(Proto_AseFep_Event, data.productionTunnel) < 65536 && pb_membersize(Proto_AseFep_Event, data.volume) < 65536 && pb_membersize(Proto_AseFep_Event, data.mute) < 65536 && pb_membersize(Proto_AseFep_Event, data.playerData) < 65536 && pb_membersize(Proto_AseFep_Event, data.dspToneTouch) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Proto_AseFep_Req_Proto_AseFep_Resp_Proto_AseFep_Event)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_AseFep_Req, data.audioMode) < 256 && pb_membersize(Proto_AseFep_Req, data.audioInput) < 256 && pb_membersize(Proto_AseFep_Req, data.positionSoundMode) < 256 && pb_membersize(Proto_AseFep_Req, data.internalSpeakerCompensation) < 256 && pb_membersize(Proto_AseFep_Req, data.dspParameter) < 256 && pb_membersize(Proto_AseFep_Req, data.dspAbsoluteVolume) < 256 && pb_membersize(Proto_AseFep_Resp, data.volume) < 256 && pb_membersize(Proto_AseFep_Resp, genericResponse) < 256 && pb_membersize(Proto_AseFep_Event, data.productionTunnel) < 256 && pb_membersize(Proto_AseFep_Event, data.volume) < 256 && pb_membersize(Proto_AseFep_Event, data.mute) < 256 && pb_membersize(Proto_AseFep_Event, data.playerData) < 256 && pb_membersize(Proto_AseFep_Event, data.dspToneTouch) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Proto_AseFep_Req_Proto_AseFep_Resp_Proto_AseFep_Event)
#endif


/* @@protoc_insertion_point(eof) */
