/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:56 2019. */

#include "ase-fep-ReqResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif




/* @@protoc_insertion_point(eof) */
