/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:56 2019. */

#include "common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_Core_GenericResponse_fields[2] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Core_GenericResponse, status, status, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
