/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:58 2019. */

#include "dsp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_Dsp_AudioMode_fields[2] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_AudioMode, mode, mode, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_AbsoluteVolume_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, Proto_Dsp_AbsoluteVolume, volume, volume, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_AbsoluteVolume, fade_duration, volume, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_RelativeVolumeChange_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_RelativeVolumeChange, volumeChange, volumeChange, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_Mute_fields[2] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, Proto_Dsp_Mute, mute, mute, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_RequestAudioInput_fields[2] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_RequestAudioInput, input, input, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_PositionSoundMode_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_PositionSoundMode, position, position, 0),
    PB_FIELD(  2, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_Dsp_PositionSoundMode, orientation, position, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_RequestPositionSoundMode_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Proto_Dsp_RequestPositionSoundMode, positionSoundMode, positionSoundMode, &Proto_Dsp_PositionSoundMode_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_ResponsePositionSoundMode_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_ResponsePositionSoundMode, error, error, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ResponsePositionSoundMode, mode, error, &Proto_Dsp_PositionSoundMode_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_InternalSpeaker_fields[4] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_InternalSpeaker, position, position, 0),
    PB_FIELD(  2, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_Dsp_InternalSpeaker, type, position, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_InternalSpeaker, compensation, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_RequestInternalSpeakerCompensation_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, Proto_Dsp_RequestInternalSpeakerCompensation, internalSpeaker, internalSpeaker, &Proto_Dsp_InternalSpeaker_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_ResponseInternalSpeakerCompensation_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_ResponseInternalSpeakerCompensation, error, error, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, Proto_Dsp_ResponseInternalSpeakerCompensation, internalSpeaker, error, &Proto_Dsp_InternalSpeaker_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_Parameter_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Dsp_Parameter, type, type, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, Proto_Dsp_Parameter, value, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_Dsp_ToneTouch_fields[9] = {
    PB_FIELD(  1, DOUBLE  , OPTIONAL, STATIC  , FIRST, Proto_Dsp_ToneTouch, Gx1, Gx1, 0),
    PB_FIELD(  2, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, Gy1, Gx1, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, Gx2, Gy1, 0),
    PB_FIELD(  4, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, Gy2, Gx2, 0),
    PB_FIELD(  5, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, Gz, Gy2, 0),
    PB_FIELD(  6, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, k5, Gz, 0),
    PB_FIELD(  7, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, k6, k5, 0),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, Proto_Dsp_ToneTouch, enabled, k6, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_Dsp_RequestPositionSoundMode, positionSoundMode) < 65536 && pb_membersize(Proto_Dsp_ResponsePositionSoundMode, mode) < 65536 && pb_membersize(Proto_Dsp_RequestInternalSpeakerCompensation, internalSpeaker) < 65536 && pb_membersize(Proto_Dsp_ResponseInternalSpeakerCompensation, internalSpeaker) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Proto_Dsp_AudioMode_Proto_Dsp_AbsoluteVolume_Proto_Dsp_RelativeVolumeChange_Proto_Dsp_Mute_Proto_Dsp_RequestAudioInput_Proto_Dsp_PositionSoundMode_Proto_Dsp_RequestPositionSoundMode_Proto_Dsp_ResponsePositionSoundMode_Proto_Dsp_InternalSpeaker_Proto_Dsp_RequestInternalSpeakerCompensation_Proto_Dsp_ResponseInternalSpeakerCompensation_Proto_Dsp_Parameter_Proto_Dsp_ToneTouch)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_Dsp_RequestPositionSoundMode, positionSoundMode) < 256 && pb_membersize(Proto_Dsp_ResponsePositionSoundMode, mode) < 256 && pb_membersize(Proto_Dsp_RequestInternalSpeakerCompensation, internalSpeaker) < 256 && pb_membersize(Proto_Dsp_ResponseInternalSpeakerCompensation, internalSpeaker) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Proto_Dsp_AudioMode_Proto_Dsp_AbsoluteVolume_Proto_Dsp_RelativeVolumeChange_Proto_Dsp_Mute_Proto_Dsp_RequestAudioInput_Proto_Dsp_PositionSoundMode_Proto_Dsp_RequestPositionSoundMode_Proto_Dsp_ResponsePositionSoundMode_Proto_Dsp_InternalSpeaker_Proto_Dsp_RequestInternalSpeakerCompensation_Proto_Dsp_ResponseInternalSpeakerCompensation_Proto_Dsp_Parameter_Proto_Dsp_ToneTouch)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
