/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:51:58 2019. */

#include "fep-ase.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_FepAse_Event_fields[4] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_FepAse_Event, type, type, 0),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , OTHER, Proto_FepAse_Event, productionTunnel, type, &Proto_Production_Tunnel_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , OTHER, Proto_FepAse_Event, overheat_info, type, &Proto_System_Overheat_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_FepAse_Req_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_FepAse_Req, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_FepAse_Req, id, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_FepAse_Resp_fields[4] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_FepAse_Resp, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_FepAse_Resp, id, type, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Proto_FepAse_Resp, genericResponse, id, &Proto_Core_GenericResponse_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_FepAse_Event, data.productionTunnel) < 65536 && pb_membersize(Proto_FepAse_Event, data.overheat_info) < 65536 && pb_membersize(Proto_FepAse_Resp, genericResponse) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Proto_FepAse_Event_Proto_FepAse_Req_Proto_FepAse_Resp)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_FepAse_Event, data.productionTunnel) < 256 && pb_membersize(Proto_FepAse_Event, data.overheat_info) < 256 && pb_membersize(Proto_FepAse_Resp, genericResponse) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Proto_FepAse_Event_Proto_FepAse_Req_Proto_FepAse_Resp)
#endif


/* @@protoc_insertion_point(eof) */
