/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:52:00 2019. */

#include "player.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_Player_Data_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_Player_Data, state, state, 0),
    PB_FIELD(  2, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_Player_Data, source, state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
