/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:52:01 2019. */

#include "production.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_Production_Tunnel_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, Proto_Production_Tunnel, data, data, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
