/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Sep 18 09:52:01 2019. */

#include "system.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_System_Overheat_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Proto_System_Overheat, amp1, amp1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Proto_System_Overheat, amp2, amp1, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Proto_System_Overheat, wfl, amp2, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, Proto_System_Overheat, wfr, wfl, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
